/**
 * API Starter
 *
 * Simple Express API ready to extend.
 * Generated by: stacksolo init --template api-starter
 */

import express from 'express';
import cors from 'cors';

const app = express();

// Middleware
app.use(cors());
app.use(express.json());

// Health check
app.get('/health', (_req, res) => {
  res.json({
    status: 'ok',
    timestamp: new Date().toISOString(),
    version: process.env.npm_package_version || '0.0.0',
  });
});

// API routes
app.get('/api', (_req, res) => {
  res.json({
    message: 'Welcome to {{projectName}} API',
    endpoints: [
      { method: 'GET', path: '/health', description: 'Health check' },
      { method: 'GET', path: '/api', description: 'This endpoint' },
      { method: 'GET', path: '/api/hello', description: 'Hello world' },
      { method: 'POST', path: '/api/echo', description: 'Echo request body' },
    ],
  });
});

// Hello endpoint
app.get('/api/hello', (_req, res) => {
  res.json({ message: 'Hello, World!' });
});

// Hello with name
app.get('/api/hello/:name', (req, res) => {
  res.json({ message: `Hello, ${req.params.name}!` });
});

// Echo endpoint - returns whatever you send
app.post('/api/echo', (req, res) => {
  res.json({
    received: req.body,
    timestamp: new Date().toISOString(),
  });
});

// 404 handler
app.use((_req, res) => {
  res.status(404).json({ error: 'Not found' });
});

// Error handler
app.use((err: Error, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
  console.error('Error:', err);
  res.status(500).json({ error: 'Internal server error' });
});

// Cloud Function entry point
export const handler = app;

// Local development
if (process.env.NODE_ENV !== 'production') {
  const port = process.env.PORT || 8080;
  app.listen(port, () => {
    console.log(`API running at http://localhost:${port}`);
    console.log(`Health check: http://localhost:${port}/health`);
  });
}
